### ISSUE TITLE
User Story - Brewery Search & Maps Tie In

### ISSUE THREAD

**Issue by neverage84** [neverage84/Project_1#3]
## User Story
As a user, I want to be able to search for local breweries in the area I'm currently located.

## Acceptance Criteria
- [x] index.html has a text input
- [x] index.html has a search button

**Comment by hirohtk** [comment]
## Acceptance Criteria
- [x] index.html has a div specifically for breweries.  
- [x] this div has classes or id's that are referenced to be populated by the AJAX call that is done in header that has input field and radio button
- [x] when input field has text, and radio button is selected to brewery, classes and id's above are filled  with elements dynamically created by JS and inserted into DOM
